package Food.Delivery.System.Payment_Service.dto;

import lombok.Data;

@Data
public class PaymentRequest {
    public Long orderId;
    public Long userId;
    public String idempotencyKey; // REQUIRED or generated by client

}
